version: "3.8"

services:
#  web:
#    build: .
#    command: python /Users/Evgen/PycharmProjects/Portal manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
  db:
    container_name: db
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data/
#    environment:
#      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

volumes:
  postgres: